// <auto-generated />
namespace ProjectFood.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class Initialderpaaa : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Initialderpaaa));
        
        string IMigrationMetadata.Id
        {
            get { return "201411241247502_Initialderpaaa"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
